### ISSUE TITLE
Summary row should support popups for selecting the kind of data to display

### ISSUE THREAD

**Issue by brendand** [brendand/mbtablegrid#10]
The summary row should provide a delegate to let it supply an NSPopupButton that lets you provide a set of options to switch between. For example, Total, Minimum, Maximum, Average, Count, if displaying aggregate data from the values in the associated main table grid's column.

**Comment by Dejal** [comment]
FYI, I've spent two hours thinking about a design for this.  This is what I've come up with; let me know if you have any feedback.  I'll implement it this afternoon.

#### Data source:

- Add a -tableGrid:footerCellForColumn: data source method similar to the -tableGrid:cellForColumn: method to get the cell for the footer.  Want a separate method so it can use a popup cell for text columns.
- Use the existing -tableGrid:formatterForColumn: method to set the formatter on the cell.
- Add a -tableGrid:footerValueForColumn: data source method similar to -tableGrid:objectValueForColumn:row: to get the footer value — the actual total or average (see below).  It can refer to the mode value if needed.
- Add a -tableGrid:footerModeForColumn: data source method to get the display mode (e.g. popup selection) — total mode, average mode, etc.  Needed to select the corresponding item in the popup.
- Add a -tableGrid:setFooterModeForColumn: data source method to set the display mode (popup selection).

#### Footer view & cell:

- MBTableGridFooterCell inherits from MBPopupButtonCell, so rename it as MBFooterPopupButtonCell, to make that more clear.  Can leave it mostly as-is.
- Move the -drawWithFrame:inView: code from the footer cell to the footer view, and leave the text drawing stuff in the cell.
- Need to add -mouseDown: etc to handle clicks; see MBTableGridHeaderView and MBTableGridContentView (the latter handles popups via -editSelectedCell:text:.).
- Add a mode property to MBFooterPopupButtonCell.
- Set the objectValue from -tableGrid:footerValueForColumn: and the mode (if supported) from -tableGrid:footerModeForColumn:.

#### Controller:

- Rename the columnWidths property as columnProperties, since it is obviously intended to store more than just widths.
- Add an implementation of -tableGrid:footerCellForColumn: to return a suitable cell:
  - For text columns, use MBFooterPopupButtonCell to allow choosing the mode (Total, Minimum, Maximum, Average or Count), and display the value.
  - For the checkbox column, return nil for the cell and draw nothing.  Or could return a mixed-state checkbox button cell that is disabled.
  - For the rating column, use a rating cell that averages the column ratings.
  - For the image column, return nil for the cell and draw nothing.
- Add an implementation of -tableGrid:footerValueForColumn: to use its knowledge of the column values to calculate an appropriate value, e.g. a total of a Price column or the average of all the Movie Ratings.
- Add an implementation of -tableGrid:footerModeForColumn: to return the mode from a dictionary, like already done for columnProperties nee columnWidths.
- Add an implementation of -tableGrid:setFooterModeForColumn: to store the mode for each column in a dictionary, like in the existing -tableGrid:setWidthForColumn:.

**Comment by brendand** [comment]
I don't think there's a need for the mode stuff. Really just need to know what type of cell to draw in the footer and let the datasource provide all the values to display plus a list of items for each popup if an NSPopupButtonCell is being used. You may want to display a count of the number of checked items, so for a checkbox column, you may still want a total displayed at the bottom. And for the rating column, you may just want to display "Average: 4.5" instead of the actual stars. But all of that can be determined by what type of footer cell is returned from the controller. The lower level code is only responsible for drawing the value obtained from footerValueForColumn.

**Comment by brendand** [comment]
I think a -tableGrid:setFooterValue:forColumn: method would be suitable to go along with the -tableGrid:footerValueForColumn: method. Then when the controller receives the value from the popup, it can do what it needs to do to remember that setting for next time.

**Comment by Dejal** [comment]
The reasoning was that the footer cell is reusable for multiple columns, so the table needs to tell it the value to display, plus the popup menu selection, since those aren't the same thing.  I thought about making the cell figure out the display value itself, but that seemed less elegant, and inconsistent with the existing design.

**Comment by Dejal** [comment]
Ah, I just noticed that you edited your comment -- I didn't get a notification of that.

I had envisioned that the popup items would be fixed.  If you want dynamic items, I'd need a data source method to update the items instead of the object value method.  In this scenario, yes, a single pair of get/set methods for the popup selection would be reasonable, in addition to the popup refresh method.

If the cell wasn't a popup (e.g. the level indicator), it could use the get method to populate its value, in the same way as a content cell (and the update and set methods wouldn't be used).

**Comment by Dejal** [comment]
Though, we may still want a separate method for the display value, since there may not be enough room to show "Average: $10.00" in the footer.  Having all the dynamic values in the popup is nice, but the footer display value should probably be shorter, either just "$10.00" or "Avg: $10.00".

**Comment by brendand** [comment]
I figured people could just widen the column to make it fit or yes, I could use "Avg: $10.00", but that's to be determined by the controller, not the grid control, so it shouldn't care about that.

This is how I currently do it with my NSTableView control:

![screen shot 2015-02-26 at 4 17 09 pm](https://cloud.githubusercontent.com/assets/586075/6404225/0456d1fc-bdd3-11e4-9cd6-5a99a8e842b6.png)

**Comment by brendand** [comment]
So I'm looking for something similar to that ^, but with the ability to have a popup there so I can change the default setting to display a different value.

**Comment by Dejal** [comment]
That's what I'll provide, then.  I've simplified my design to fit with what you want, and have spent a couple of hours on it tonight, and will finish it tomorrow (perhaps about another 3 hours).

**Comment by Dejal** [comment]
I've now completed this.  Take a look and let me know if you find any issues or want any tweaks.

![150227 footer](https://cloud.githubusercontent.com/assets/1318849/6425001/a8ba6142-bec7-11e4-9b13-81c4a8bb729a.png)

**Comment by brendand** [comment]
:+1:
