### ISSUE TITLE
Clicking on a popup button cell and not selecting a value clears the existing value

### ISSUE THREAD

**Issue by brendand** [brendand/mbtablegrid#31]
If you don't choose a value from the popup button, the existing value should remain. Currently it's clearing the current value from the cell.

**Comment by kdbdallas** [comment]
Related to commit 87ef33e132c5db6ffd729f6eb9438608329c56a3 "Fixed PopupButtonCells Always Showing First Value as Selected/Checked  When Opened"

**Comment by brendand** [comment]
I'm still able to reproduce this problem.

![popup misbehaviour](https://dl.dropboxusercontent.com/s/zn92iw8h1gnv5bj/694C183B-DBF6-41F6-B4BC-306E8D032AFF-878-0002666121906DE9.gif?dl=0)

Also notice how when you select the value from the other popup, then it refreshes the original.

**Comment by kdbdallas** [comment]
Right the commit above was not a fix for this issue, it was just 'related' to this issue.
The issue that was fixed was that, no matter which value you selected the first value in the list would ALWAYS show with the checkmark.
I fixed it so that the checkmark shows correctly with the item that is actually selected.

**Comment by brendand** [comment]
Oh I see. Sorry, my mistake. Thanks for fixing that one.
